twitter/twitter/urls.py
from django.contrib import admin
from django.urls import path
from tweet.views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='tweet/login.html')),
    path("", LoginUserView.as_view(), name="login_user"),
    path("logout/", LogoutUserView.as_view(), name="logout_user"),
    path("create_user/", CreateUserView.as_view(), name="create_user"),
    path("add_message/", AddMessageView.as_view(), name="add_message"),
    path("mark/<int:id>/", MarkMessageView.as_view(), name="mark"),
    path("like/<int:msg_id>/", LikeMessageView.as_view(), name="like"),
    path("create/<int:message_id>/", AddCommentView.as_view(), name="add_comment"),
    path("user_info/<int:user_id>/", GetUserInfoView.as_view(), name="user_info"),
    path("user_profile/<int:user_id>", GetUserProfileView.as_view(), name="user_profile"),
    path("password/", ChangeUserPasswordView.as_view(), name="change_password"),
    path("edit_profile/<int:user_id>/", EditUserProfileView.as_view(), name="edit_profile"),
    path("user_profile/api/charts/", DataForAllMessagesChartsView.as_view(),name="data_charts"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/tweet/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    USERNAME_FIELD = 'email'
    email = models.EmailField(('email address'), unique=True)
    image = models.FileField(upload_to="profile_img", blank=True)
    twitter = models.URLField(max_length=256, null=True, blank=True)
    facebook = models.URLField(max_length=256, null=True, blank=True)
    google = models.URLField(max_length=256, null=True, blank=True)
    behance = models.URLField(max_length=256, null=True, blank=True)
    REQUIRED_FIELDS = ["username"]


class Message(models.Model):
    content = models.CharField(max_length=140, null=False)
    creation_date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.CharField(max_length=60, null=False)
    creation_date = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE)


class PersonalMessage(models.Model):
    content = models.CharField(max_length=140, null=False)
    creation_date = models.DateTimeField(auto_now_add=True)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="from_user")
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="to_user")


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, default="1")
    created = models.DateTimeField(auto_now_add=True)

twitter/tweet/forms.py
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import CharField, TextInput

from tweet.models import User, Message, Comment, PersonalMessage


class LoginUserForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=64)
    passwd = forms.CharField(label="Password", widget=forms.PasswordInput)


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True)


    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']

    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.first_name = self.cleaned_data.get("first_name")
        user.last_name = self.cleaned_data.get("last_name")
        user.email = self.cleaned_data.get("email")
        if commit:
            user.save()
        return user


class AddMessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = "__all__"
        exclude = ['created_by', 'is_read']
        widgets = {
            'content': TextInput(attrs={'placeholder': 'Type your message here'})
        }
        labels = {
            'content': '',
        }


class AddCommentForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]


class AddPvrMsgForm(forms.ModelForm):
    class Meta:
        model = PersonalMessage
        fields = "__all__"
        exclude = ["from_user", "to_user"]
        widgets = {
            'content': TextInput(attrs={'placeholder': 'Type your message here'})
        }
        labels = {
            'content': '',
        }

class EditUserForm(forms.ModelForm):
    twitter = forms.CharField(required=False)
    facebook = forms.CharField(required=False)
    google = forms.CharField(required=False)
    behance = forms.CharField(required=False)
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "image", "twitter", "facebook", "google", "behance"]

twitter/tweet/views.py
import datetime
import itertools

from bootstrap_modal_forms.mixins import PassRequestMixin
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView
from django.db.models import Q, Count
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from tweet.forms import *
from tweet.models import *


def date_generator():
    from_date = datetime.datetime.today()
    while True:
        yield from_date
        from_date = from_date - datetime.timedelta(days=1)


class LoginUserView(View):
    def get(self, request):
        form = LoginUserForm()
        return render(request, "tweet/login.html", locals())

    def post(self, request):
        form = LoginUserForm(request.POST)
        if form.is_valid():
            email = request.POST.get("email")
            passwd = request.POST.get("passwd")
            user = authenticate(email=email, password=passwd)
            if user:
                login(request, user)
                return redirect("add_message")
            form.add_error("email", "Zły login albo hasło")
            message = "zły login lub hasło"
        return render(request, "tweet/login.html", locals())


class LogoutUserView(View):
    def get(self, request):
        logout(request)
        return redirect("login_user")


class CreateUserView(View):
    def get(self, request):
        form = CreateUserForm()
        return render(request, "tweet/create_user.html", locals())

    def post(self, request):
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Konto zostało utworzone')
            user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password1'])
            if user:
                login(request, user)
            return redirect('add_message')
        return render(request, "tweet/create_user.html", locals())


class AddMessageView(LoginRequiredMixin, View):

    def get(self, request):
        form = AddMessageForm()
        messages = Message.objects.all().order_by("-creation_date")
        comments = Comment.objects.all().order_by("creation_date")
        users = User.objects.all().order_by("username")
        likes = []
        for msg in messages:
            user_likes_this = msg.like_set.filter(user=request.user)
            for like in user_likes_this:
                likes.append(like.message)
        return render(request, "tweet/posts_list.html", locals())

    def post(self, request):
        messages = Message.objects.all()
        form = AddMessageForm(request.POST)
        if form.is_valid():
            message = Message()
            user = request.user
            message.created_by = user
            message.content = request.POST.get("content")
            message.creation_date = request.POST.get("creation_date")
            message.save()
            return redirect("add_message")
        return render(request, "tweet/posts_list.html", locals())


class MarkMessageView(LoginRequiredMixin, View):
    def get(self, request, id):
        message = Message.objects.get(pk=id)
        if not message.is_read:
            message.is_read = True
        else:
            message.is_read = False
        message.save()
        return redirect("add_message")


class LikeMessageView(LoginRequiredMixin, View):
    def get(self, request, msg_id):
        to_like = Message.objects.get(pk=msg_id)
        author = to_like.created_by
        if author != request.user:
            Like.objects.get_or_create(user=request.user, message_id=msg_id)
        return redirect("add_message")


class AddCommentView(LoginRequiredMixin, PassRequestMixin, SuccessMessageMixin, CreateView):
    template_name = 'tweet/add_comment.html'
    form_class = AddCommentForm
    success_url = reverse_lazy('add_message')

    def form_valid(self, form):
        message = Message.objects.get(pk=self.kwargs['message_id'])
        form.instance.created_by = self.request.user
        form.instance.message = message
        return super(AddCommentView, self).form_valid(form)


class GetUserInfoView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        form = AddPvrMsgForm()
        about_user = User.objects.get(pk=user_id)
        messages = Message.objects.filter(created_by=about_user).count()
        pvr_messages = PersonalMessage.objects.filter(Q(from_user=user_id) | Q(to_user=user_id)).order_by(
            "-creation_date")
        return render(request, "tweet/user_info.html", locals())

    def post(self, request, user_id):
        form = AddPvrMsgForm(request.POST)
        about_user = User.objects.get(pk=user_id)
        messages = Message.objects.filter(created_by=about_user).count()
        pvr_messages = PersonalMessage.objects.filter(Q(from_user=user_id) | Q(to_user=user_id))
        if form.is_valid():
            pvr_msg = PersonalMessage()
            from_user = request.user
            pvr_msg.content = request.POST.get("content")
            pvr_msg.creation_date = request.POST.get("creation_date")
            pvr_msg.from_user = from_user
            pvr_msg.to_user = about_user
            pvr_msg.save()
            return redirect("user_info", about_user.id)
        return render(request, "tweet/user_info.html", locals())


class GetUserProfileView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user_profile = User.objects.get(pk=user_id)
        msg = Message.objects.filter(created_by=user_profile).count()
        msgs = Message.objects.filter(created_by=user_profile).order_by("-creation_date")
        likes = Like.objects.filter(user=user_id)
        return render(request, "tweet/user_profile.html", locals())


class ChangeUserPasswordView(LoginRequiredMixin, View):
    def get(self, request):
        form = PasswordChangeForm(request.user)
        return render(request, 'tweet/change_password.html', locals())

    def post(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Your password was successfully updated!")
            return redirect("user_profile", user.id)
        else:
            messages.error(request, "An error occured. Try again.")
        return render(request, "tweet/change_password.html", locals())


class EditUserProfileView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        edit_user = User.objects.get(pk=user_id)
        form = EditUserForm(instance=edit_user)
        return render(request, "tweet/edit_profile.html", locals())

    def post(self, request, user_id):
        edit_user = User.objects.get(pk=user_id)
        form = EditUserForm(request.POST, request.FILES, instance=edit_user)
        if form.is_valid():
            edit_user.username = request.POST.get("username")
            edit_user.email = request.POST.get("email")
            edit_user.first_name = request.POST.get("first_name")
            edit_user.last_name = request.POST.get("last_name")
            edit_user.image = request.FILES.get('image')
            edit_user.twitter = request.POST.get("twitter")
            edit_user.google = request.POST.get("google")
            edit_user.facebook = request.POST.get("facebook")
            edit_user.behance = request.POST.get("behance")
            edit_user.save(
                update_fields=["username", "email", "first_name", "last_name", "image", "twitter", "google", "facebook",
                               "behance"])
            messages.success(request, "Your profile was successfully updated!")
            return redirect("user_profile", edit_user.id)
        else:
            messages.error(request, "An error occured. Try again.")
        return render(request, "tweet/edit_profile.html", locals())


class DataForAllMessagesChartsView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, format=None):
        labels = []
        all_messages = []
        user_messages = []
        dates = itertools.islice(date_generator(), 7)
        for date in dates:
            labels.append(date.strftime('%Y-%m-%d'))
            all_messages.append(Message.objects.filter(creation_date__day=date.day, creation_date__month=date.month,
                                                        creation_date__year=date.year).count())
            user_messages.append(Message.objects.filter(creation_date__day=date.day, creation_date__month=date.month,
                                                        creation_date__year=date.year,created_by=request.user).count())
        labels.reverse()
        all_messages.reverse()
        user_messages.reverse()
        data = {
            "labels": labels,
            "all": all_messages,
            "user": user_messages
        }

        print(request.user)
        return Response(data)

twitter/tweet/templates/tweet/add_comment.html
<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title">Add comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">
        {% if message.created_by != user.username %}
        {% for field in form %}
            <div class="form-group{% if field.errors %} invalid{% endif %}">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% for error in field.errors %}
                    <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
        {% endif %}
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="submit-btn btn btn-primary">Add</button>
    </div>
</form>

twitter/tweet/templates/tweet/add_message.html
<form method="POST">
    {% csrf_token %}
    <div class="type_msg">
        <div class="input_msg_write">
            {{ form.as_p }}
            <button class="msg_send_btn" type="submit"><i class="far fa-paper-plane" aria-hidden="true"></i></button>
        </div>
    </div>
</form>

twitter/tweet/templates/tweet/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Python Twitter</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'tweet/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>
</head>

<body>

{% block nav %}

{% endblock %}

{% block title %}
    {% include 'tweet/title.html' %}
{% endblock %}

{% block content %}

{% endblock %}
<script>
    $(document).ready(function () {
        {% block jquery %}{% endblock %}
    })
</script>
</body>
<footer class="page-footer font-small fixed-bottom">
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> GitHub</a>
  </div>
</footer>
</html>

twitter/tweet/templates/tweet/change_password.html
{% extends 'tweet/base.html' %}
{% block nav %}
    {% include 'tweet/navbar.html' %}
{% endblock %}
{% block title %}

{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="password_form">
                <h4>Change your password</h4>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-outline-success pull-right" type="submit">Save changes</button>
                     <a href="{% url "user_profile" user.id %}"><button class="btn btn-outline-info pull-left">Back to Profile</button></a>
                </form>
            </div>

        </div>
    </div>

{% endblock %}

twitter/tweet/templates/tweet/edit_profile.html
{% extends 'tweet/base.html' %}
{% block nav %}
    {% include 'tweet/navbar.html' %}
{% endblock %}
{% block title %}

{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="edit_form">
                <h4>Edit Your Profile</h4>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-outline-success pull-right" type="submit">Save changes</button>
                    <a href="{% url "user_profile" user.id %}"><button class="btn btn-outline-info pull-left">Back to Profile</button></a>
                </form>
            </div>

        </div>
    </div>

{% endblock %}

twitter/tweet/templates/tweet/login.html
{% extends 'tweet/base.html' %}
{% block content %}
    <div class="container" style="display: flex">
        <div class=row">
            <div class="login_form" style="margin-left: 22vw">
                <fieldset>
                    <legend style="padding: 20px">Logowanie do Twittera</legend>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Log In">
                    </form>
                    <br>
                    <p>Need account? Click <a href="{% url "create_user" %}">here</a></p>
                </fieldset>
            </div>
        </div>
    </div>
{% endblock %}

twitter/tweet/templates/tweet/message_list.html
{% for message in messages %}

    <div class="chat_list">
        <div class="chat_ib">
            <h5>
                <b>Created by:</b> {{ message.created_by }}
                <span class="chat_date">{{ message.creation_date }}</span>
            </h5>
            <p class="post_content">{{ message.content }}</p>

            <span class="buttons_bar">
                {% if message.created_by != user %}
                {% if message.is_read == True %}
                    <a href="{% url "mark" message.id %}"><button class="add-comment" type="button"><i
                            class="fa fa-envelope-open" aria-hidden="true"></i></button></a>
                {% else %}
                    <a href="{% url "mark" message.id %}"><button class="add-comment" type="button"><i
                            class="fa fa-envelope" aria-hidden="true"></i></button></a>
                {% endif %}
                <button class="add-comment" type="button" name="comment_btn" data-id="{% url "add_comment" message.pk %}">
                    <i class="fa fa-comment" aria-hidden="true"></i>
                </button>
                {% if message in likes %}
                    <a href="{% url "like" message.id %}"><button class="add-comment" type="button" name="like_btn">
                        <i class="fas fa-heart"></i>
                    </button></a>
                {% else %}
                    <a href="{% url "like" message.id %}"><button class="add-comment" type="button" name="like_btn">
                        <i class="far fa-heart"></i>
                    </button></a>
                {% endif %}
                {% endif %}
                <span class="likes">{{ message.like_set.count }} likes this post</span>
            </span>


        </div>
    </div>
    {% for comment in comments %}
        {% if message.id == comment.message.id %}
            <div class="comment_list">
                <div class="comment_ib">
                    <h5>
                        <b>Created by:</b> {{ comment.created_by }}
                        <span class="comment_date">{{ comment.creation_date }}</span>
                    </h5>
                    <p>{{ comment.content }}</p>
                </div>
            </div>
        {% endif %}
    {% endfor %}

{% endfor %}



<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(".add-comment").each(function () {
            $(this).modalForm({formURL: $(this).data('id')});
        });
    });
</script>

twitter/tweet/templates/tweet/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Twitter</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url "add_message" %}">All Messages</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "user_profile" user.id%}">User Profile</a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url "logout_user" %}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url "login_user" %}">Login</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">User: {% if user.is_authenticated %}
                    {{ user}}
                {% else %}
                    Unknown
                {% endif %}
                </a></li>
        </ul>
    </div>
</nav>

twitter/tweet/templates/tweet/personal_messages.html
{% for pvr_message in pvr_messages %}
    {% if pvr_message.to_user == user or pvr_message.from_user == user %}
        <div class="{% if pvr_message.from_user == user %} outgoing_msg {% else %} incoming_msg{% endif %}">
            <div class="{% if pvr_message.from_user == user %} sent_msg {% else %} received_msg{% endif %}">
                {% if pvr_message.from_user != user %}
                    <div class="received_withd_msg">
                        <p>{{ pvr_message.content }}</p>
                        <span class="time_date"> {{ pvr_message.creation_date }}</span>
                    </div>
                {% else %}
                    <p>{{ pvr_message.content }}</p>
                    <span class="time_date"> {{ pvr_message.creation_date }}</span>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endfor %}

twitter/tweet/templates/tweet/posts_list.html
{% extends 'tweet/base.html' %}
{% block nav %}
    {% include 'tweet/navbar.html' %}
{% endblock %}
{% block title %}

{% endblock %}
{% block content %}
    <div class="container">
        <div class=row">
            <div class="chat">
                <section class="sidebar">
                    <div class="user-info">
                        {% include 'tweet/user.html' %}
                    </div>
                    <div class="friends-list">
                        {% include 'tweet/users_list.html' %}
                    </div>
                </section>

                <section class="main">
                    <div class="message-list">
                        {% include 'tweet/message_list.html' %}
                    </div>
                    {% include 'tweet/add_message.html' %}
                </section>
            </div>
        </div>
    </div>

{% endblock %}

twitter/tweet/templates/tweet/title.html
<div class="container">
    <div class="row">
        <h1 style="margin: 50px auto">Python Twitter</h1>
    </div>
</div>

twitter/tweet/templates/tweet/user.html
<h4>Current User</h4>
<p>
    {{ user.first_name }} {{ user.last_name }}<br>
</p>
<p>
    Posts: {{ user.message_set.count }}
</p>

twitter/tweet/templates/tweet/users_list.html
<h4>Users List</h4>
{% for u in users %}
    {% if u.username != user.username %}
        <div class="user">
            <span><a href="{% url "user_info" u.id %}">{{ u.first_name }} {{ u.last_name }}</a></span>
        </div>

    {% endif %}
{% endfor %}